$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: machine_failure_training_pipeline
experiment_name: machine-failure-training
description: Training pipeline to predict machine failure using Decision Tree classifier

# --------------------------------------------------------------------
# INPUTS & OUTPUTS
# --------------------------------------------------------------------
inputs:
  input_data:
    type: uri_file
    path: azureml:machine-failure-data@latest

outputs:
  train_data:
  test_data:
  model_info_output_path:

# --------------------------------------------------------------------
# PIPELINE SETTINGS
# --------------------------------------------------------------------
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

# --------------------------------------------------------------------
# JOBS
# --------------------------------------------------------------------
jobs:

  # -----------------------------
  # 1️⃣ Data Preparation Step
  # -----------------------------
  prep_data:
    type: command
    display_name: prep-data
    code: mlops/data-science/src        # ✅ Corrected from ../../../data-science/src
    command: >
      python prep.py
      --raw_data ${{inputs.raw_data}}
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:machine-failure-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.input_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  # -----------------------------
  # 2️⃣ Training (Hyperparameter Sweep)
  # -----------------------------
  sweep_step:
    type: sweep
    display_name: decision-tree-sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    trial: mlops/azureml/train/train.yml   # ✅ Corrected path
    sampling_algorithm: random
    search_space:
      criterion:
        type: choice
        values: ["gini", "entropy"]
      max_depth:
        type: choice
        values: [1, 3, 5, 10]
    objective:
      goal: maximize
      primary_metric: Accuracy
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  # -----------------------------
  # 3️⃣ Model Registration
  # -----------------------------
  register_model:
    type: command
    display_name: register-model
    code: mlops/data-science/src          # ✅ Corrected path
    command: >
      python register.py
      --model_name ${{inputs.model_name}}
      --model_path ${{inputs.model_path}}
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:machine-failure-train-env@latest
    inputs:
      model_name: "machine_failure_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
